package service;

import java.math.BigDecimal;
import java.util.List;

import entity.ProductEntity;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import repository.ProductRepository;

@ApplicationScoped
public class ProductService {

    @Inject
    private ProductRepository productRepository;

    public void createProduct(String code, String name, BigDecimal price) {
        // maybe code should be generated by the system, not provided by the user
        ProductEntity product = new ProductEntity(code, name, price);
        productRepository.persist(product);
    }

    public entity.ProductEntity getProductByCode(String code) {
        return productRepository.find("code", code).firstResult();
    }

    public List<ProductEntity> getAllProducts() {
        return productRepository.listAll();
    }
}
