package service;

import java.util.List;

import entity.RawMaterialEntity;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import repository.RawMaterialRepository;

@ApplicationScoped
public class RawMaterialService {

    @Inject
    private RawMaterialRepository rawMaterialRepository;

    public RawMaterialEntity createRawMaterial(String name, Integer quantity) {
        // maybe code should be generated by the system, not provided by the user
        RawMaterialEntity rawMaterial = new RawMaterialEntity(name, quantity);
        rawMaterialRepository.persist(rawMaterial);
        return rawMaterial;
    }

    public List<RawMaterialEntity> getRawMaterialByCode() {
        return rawMaterialRepository.listAll();
    }

    public RawMaterialEntity updateRawMaterial(Long code, RawMaterialEntity updatedRawMaterial) {
        RawMaterialEntity rawMaterial = rawMaterialRepository.findById(code);

        if (rawMaterial == null) {
            return null; // or throw an exception, or return a Response with an error status
        }

        // Just Change what's being changed
        if (updatedRawMaterial.getName() != null) {
            rawMaterial.setName(updatedRawMaterial.getName());
        }

        if (updatedRawMaterial.getQuantity() != null) {
            rawMaterial.setQuantity(updatedRawMaterial.getQuantity());
        }

        rawMaterialRepository.persist(rawMaterial);

        return rawMaterial;
    }

    public boolean deleteRawMaterial(Long code) {
        RawMaterialEntity rawMaterial = rawMaterialRepository.findById(code);

        if (rawMaterial == null) {
            return false;
        }

        rawMaterialRepository.deleteById(code);
        return true;
    }
}