package service;

import entity.RawMaterialEntity;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import repository.RawMaterialRepository;

@ApplicationScoped
public class RawMaterialService {
    @Inject
    private RawMaterialRepository rawMaterialRepository;

    public void createRawMaterial(String code, String name, Integer quantity) {
        // maybe code should be generated by the system, not provided by the user
        RawMaterialEntity rawMaterial = new RawMaterialEntity(code, name, quantity);
        rawMaterialRepository.persist(rawMaterial);
    }

    public RawMaterialEntity getRawMaterialByCode(String code) {
        return rawMaterialRepository.find("code", code).firstResult();
    }
}
