package entity;

import java.math.BigDecimal;

import io.quarkus.hibernate.orm.panache.PanacheEntity;
import jakarta.persistence.Cacheable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;

@Entity(name = "products")
@Cacheable
public class ProductEntity extends PanacheEntity {

    @Column(unique = true)
    private String code;

    private String name;

    private BigDecimal price;

    public ProductEntity() {
    }

    public ProductEntity(String code, String name, BigDecimal price) {
        // maybe code should be generated by the system, not provided by the user
        this.code = code;
        this.name = name;
        this.price = price;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}
