package entity;

import java.math.BigDecimal;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.Cacheable;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

@Entity(name = "products")
@Cacheable
public class ProductEntity extends PanacheEntityBase {

    @Id
    @GeneratedValue
    private Long code;

    private String name;

    private BigDecimal price;

    public ProductEntity() {
    }

    public ProductEntity(String name, BigDecimal price) {
        // using the id generated by Panache as the code since it is unique and
        // auto-generated
        this.name = name;
        this.price = price;
    }

    public Long getCode() {
        return this.code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}
