package entity;

import io.quarkus.hibernate.orm.panache.PanacheEntity;
import jakarta.persistence.Cacheable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;

@Entity(name = "raw_materials")
@Cacheable
public class RawMaterialEntity extends PanacheEntity {
    @Column(unique = true)
    private String code;

    private String name;

    private Integer quantity;

    public RawMaterialEntity() {
    }

    public RawMaterialEntity(String code, String name, Integer quantity) {
        // maybe code should be generated by the system, not provided by the user
        this.code = code;
        this.name = name;
        this.quantity = quantity;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}
