package entity;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.Cacheable;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

@Entity(name = "raw_materials")
@Cacheable
public class RawMaterialEntity extends PanacheEntityBase {

    @Id
    @GeneratedValue
    private Long code;

    private String name;

    private Integer quantity;

    public RawMaterialEntity() {
    }

    public RawMaterialEntity(String name, Integer quantity) {
        // using the id generated by Panache as the code since it is unique and
        // auto-generated
        this.name = name;
        this.quantity = quantity;
    }

    public Long getCode() {
        return this.code;
    }

    public void setCode(Long code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}
